repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ['--unsafe']
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        language_version: python3.9
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        args:
            [
                "--line-width=88", # isort ignores this value in pyproject.toml
                "--profile=black"
            ]
        language: system
        types: [ python ]
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        language: system
        entry: mypy
        args:
            [
                "--config-file",
                "mypy.ini"
            ]
        types: [ python ]
        exclude: tasks/
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3.9